// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3tFVBUP57DDtDdarlJCju6Un02SdtbPA',
    appId: '1:900652632563:web:b6253cd4187f131f1f6a86',
    messagingSenderId: '900652632563',
    projectId: 'ridezzy-vvj1mf',
    authDomain: 'ridezzy-vvj1mf.firebaseapp.com',
    storageBucket: 'ridezzy-vvj1mf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4s39Kjcfl59nSqCZr6vEEwao5Mrd9mUY',
    appId: '1:900652632563:android:59d7b77320b42dd01f6a86',
    messagingSenderId: '900652632563',
    projectId: 'ridezzy-vvj1mf',
    storageBucket: 'ridezzy-vvj1mf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnz42x9b_5VBDVipJn6R0dGDTXr8mX-yY',
    appId: '1:900652632563:ios:bfa45cd4acc3a95e1f6a86',
    messagingSenderId: '900652632563',
    projectId: 'ridezzy-vvj1mf',
    storageBucket: 'ridezzy-vvj1mf.firebasestorage.app',
    androidClientId: '900652632563-2mo9dsmq997m5vqrd9m9umss9kspfbh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridezzyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnz42x9b_5VBDVipJn6R0dGDTXr8mX-yY',
    appId: '1:900652632563:ios:bfa45cd4acc3a95e1f6a86',
    messagingSenderId: '900652632563',
    projectId: 'ridezzy-vvj1mf',
    storageBucket: 'ridezzy-vvj1mf.firebasestorage.app',
    androidClientId: '900652632563-2mo9dsmq997m5vqrd9m9umss9kspfbh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridezzyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3tFVBUP57DDtDdarlJCju6Un02SdtbPA',
    appId: '1:900652632563:web:cdeac071a98464f71f6a86',
    messagingSenderId: '900652632563',
    projectId: 'ridezzy-vvj1mf',
    authDomain: 'ridezzy-vvj1mf.firebaseapp.com',
    storageBucket: 'ridezzy-vvj1mf.firebasestorage.app',
  );
}
