// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSuSiylAIdq8sjOBjV0onVT7NhbgwXAEM',
    appId: '1:335767963568:web:2ef67caae916100b517875',
    messagingSenderId: '335767963568',
    projectId: 'shipryd-2026',
    authDomain: 'shipryd-2026.firebaseapp.com',
    databaseURL: 'https://shipryd-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shipryd-2026.firebasestorage.app',
    measurementId: 'G-FNBHVG61LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6q1NImvNF9kmAFbcp9dT52x_6MpW1Yus',
    appId: '1:335767963568:android:2787fb892fb7c228517875',
    messagingSenderId: '335767963568',
    projectId: 'shipryd-2026',
    databaseURL: 'https://shipryd-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shipryd-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNIseNLxi1WMprYlm8uQvrsR-yxiNNABA',
    appId: '1:335767963568:ios:b29c4791557f3762517875',
    messagingSenderId: '335767963568',
    projectId: 'shipryd-2026',
    databaseURL: 'https://shipryd-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shipryd-2026.firebasestorage.app',
    iosBundleId: 'com.example.ridezzyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNIseNLxi1WMprYlm8uQvrsR-yxiNNABA',
    appId: '1:335767963568:ios:b29c4791557f3762517875',
    messagingSenderId: '335767963568',
    projectId: 'shipryd-2026',
    databaseURL: 'https://shipryd-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shipryd-2026.firebasestorage.app',
    iosBundleId: 'com.example.ridezzyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSuSiylAIdq8sjOBjV0onVT7NhbgwXAEM',
    appId: '1:335767963568:web:d0501a51a28978ce517875',
    messagingSenderId: '335767963568',
    projectId: 'shipryd-2026',
    authDomain: 'shipryd-2026.firebaseapp.com',
    databaseURL: 'https://shipryd-2026-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shipryd-2026.firebasestorage.app',
    measurementId: 'G-LBN8VHD9BV',
  );

}